server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  cache:
      type: REDIS
      redis:
        cache-null-values: false
        time-to-live: 300000ms
        use-key-prefix: true
      cache-names: userCache,allUsersCache  # 缓存名称列表
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345  # redis服务器连接密码
    database: 0  # 数据库索引 默认为0
    lettuce:    # spring 2.0后默认的java客户端
      shutdown-timeout: 200ms # 连接超时时间
      pool:
        max-active: 7   # 连接池最大连接数(<0 无限制)
        max-wait: -1ms  # 连接池最大阻塞等待时间(<0 无限制)
        max-idle: 7     # 连接池最大空闲连接
        min-idle: 2     # 连接池最小空闲连接

mybatis-plus:
  # 因maven打包后, xml文件位于com.learn....包下,所以不能配置为com/learn/....
  mapper-locations: classpath*:com.learn.cache/dao/repository/*.xml
  # 实体扫描
  typeAliasesPackage: >
    com.learn.cache.dao.entity
  global-config:
    id-type: 2      # 0:数据库ID自增   1:用户输入ID   2:全局唯一(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true       # 配置的缓存的 全局开关
    lazyLoadingEnabled: true    # 延时加载 开关
    multipleResultSetsEnabled: true  # 开启 延时加载一个属性时会加载对象全部属性, 不开启 按需加载属性

logging:
  level:
    ROOT: INFO
    com:
      learn: DEBUG
  file: D:/logs/boot-redis-cache.log