spring:
  application:
    name: hystrix-eureka

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/