server:
  port: 8004

spring:
  application:
    name: gugpay-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:      # 注入consul
        service-name: gugpay-gateway

zuul:
  ignored-services: "*"
  routes:
    servcie-api:
      path: /**
      service-id: gugpay-service
  retryable: true       # 重试开启

management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh  # 开启config client: refresh对单个配置的更新, bus-refresh 对总线上的全部更新
      base-path: /

logging:
  file:
    path: ./log/gugpay-gateway.log