server:
  port: 8000

spring:
  application:
    name: config-eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/