spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxpay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 10
    minIdle: 3
    maxActive: 60
    timeBetweenEvicationRunsMillis: 60000
    minEvicatabledTimeMillis: 300000
    validationQuery: "SELECT 'x'"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedPerConnectionSize: 50
    filters: "stat"
